import ReactMarkdown from 'react-markdown';
import type { Itinerary, ItineraryDay } from '../types/itinerary';

export type Props = {
  itinerary: Itinerary;
  totalCostUsd?: number;
};

function formatDay(d: ItineraryDay): string {
  const lines: string[] = [];
  lines.push(`### Day ${d.day} — ${d.date} · ${d.theme}`);
  lines.push(
    `**Weather:** ${d.weather.summary} (${Math.round(d.weather.lowC)}°–${Math.round(d.weather.highC)}°C)`,
  );
  lines.push('');
  lines.push('**Morning**');
  for (const m of d.morning) lines.push(`- ${m}`);
  lines.push('');
  lines.push('**Afternoon**');
  for (const m of d.afternoon) lines.push(`- ${m}`);
  lines.push('');
  lines.push('**Evening**');
  for (const m of d.evening) lines.push(`- ${m}`);
  lines.push('');
  lines.push(`**Meals:** 🥐 ${d.meals.breakfast} · 🥗 ${d.meals.lunch} · 🍽️ ${d.meals.dinner}`);
  lines.push('');
  lines.push(`**Transport:** ${d.transport}`);
  lines.push('');
  lines.push(`**Day cost (est.):** $${Math.round(d.estimatedCostUsd)}`);
  return lines.join('\n');
}

function toMarkdown(it: Itinerary, totalCostUsd?: number): string {
  const lines: string[] = [];
  lines.push(`# Trip to ${it.destination}`);
  lines.push(
    `**${it.totalDays} day(s)** starting **${it.startDate}** · budget tier: **${it.budgetTier}** · est. **$${Math.round(it.totalEstimatedCostUsd)}**`,
  );
  lines.push('');
  lines.push(`> ${it.summary}`);
  lines.push('');
  lines.push('## Packing tips');
  for (const tip of it.packingTips) lines.push(`- ${tip}`);
  lines.push('');
  lines.push('## Day-by-day');
  for (const d of it.days) {
    lines.push(formatDay(d));
    lines.push('');
  }
  if (typeof totalCostUsd === 'number' && totalCostUsd > 0) {
    lines.push('---');
    lines.push(`_Generated by ${'`'}5 specialist agents${'`'} + supervisor · Anthropic API cost: $${totalCostUsd.toFixed(4)}_`);
  }
  return lines.join('\n');
}

export default function ItineraryView({ itinerary, totalCostUsd }: Props) {
  return (
    <article className="prose prose-slate max-w-none rounded-xl border border-slate-200 bg-white p-6 shadow-sm prose-h1:mb-2 prose-h2:mt-6 prose-h3:mt-5">
      <ReactMarkdown>{toMarkdown(itinerary, totalCostUsd)}</ReactMarkdown>
    </article>
  );
}
